# Generated by Django 4.2.10 on 2025-07-16 01:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_date_created', models.DateTimeField(blank=True, null=True)),
                ('verified_date_changed', models.DateTimeField(auto_now=True)),
                ('verified_count', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('verified_count', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('last_device_failed_date', models.DateTimeField(blank=True, null=True)),
                ('last_device_failed_ip_addr_v4', models.CharField(max_length=50, null=True)),
                ('last_device_failed_ip_addr_v6', models.CharField(max_length=50, null=True)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_safe', models.BooleanField(default=False)),
                ('score', models.FloatField()),
                ('current_score_enhanced', models.FloatField(null=True)),
                ('ja4', models.CharField(max_length=100, null=True)),
                ('ja4h', models.CharField(max_length=100, null=True)),
                ('ja4l', models.CharField(max_length=100, null=True)),
                ('ja3', models.CharField(max_length=1000, null=True)),
                ('get_header_signature', models.CharField(max_length=200, null=True)),
                ('post_header_signature', models.CharField(max_length=200, null=True)),
                ('content_length', models.CharField(max_length=50, null=True)),
                ('source_ipv4', models.CharField(max_length=50, null=True)),
                ('user_agent', models.CharField(max_length=500)),
                ('reason', models.CharField(max_length=500, null=True)),
                ('source', models.CharField(default='API Call', max_length=100, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.devices')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='devices',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.user'),
        ),
    ]
